### ISSUE TITLE
Clicking on a waypoint should not adjust zoom when centering the waypoint

### ISSUE THREAD

**Issue by RobotCaleb** [SjorsWijsman/dmz-key-locations#14]
I zoomed in for a reason. I don't want it to zoom out to show me what I clicked on. I know what I clicked on and only want it to pop up and show me information. Preferably without even centering the waypoint

**Comment by SjorsWijsman** [comment]
Heya, the map now no longer zooms you out when you click on a marker, I do like the centering as this also helps bring the video in frame on smaller devices. Thanks for submitting!
