### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by ninjamonkno1** [SjorsWijsman/dmz-key-locations#21]
Hey, the main website is down and showing a GitHub pages not found. 

Love this tool and missed not having it last night.

**Comment by ninjamonkno1** [comment]
It’s back up 😁👍

**Comment by SjorsWijsman** [comment]
Thanks for letting me know, I did a host migration yesterday from Github Pages to Vercel, which means we had to do some dns changes. I think these are still updating causing 404s for some people, should be fixed for everyone today/tomorrow.
