### ISSUE TITLE
Plan for Ashika Island?

### ISSUE THREAD

**Issue by Be-Like** [SjorsWijsman/dmz-key-locations#24]
What is your plan for Ashika Island? I'm a developer and am more than happy to help out if needed. I've never worked with Svelte, but I'm sure it won't be an issue. I generally work with Vue and JavaScript. 

Also, have you thought about making it easier for people to add a location via the application? I assume that isn't the case because there is no hosted backend.

**Comment by SjorsWijsman** [comment]
Working on a toggle to switch between the maps right now, hopefully will get that out this week. Gathering the new locations for Ashika Island while I'm working on it. 

I don't want the hassle that comes with setting up a database and all that stuff just so people can suggest new locations. So for now people can make pull requests as all the data is quite easy to find in the code (or contact me through the discord server). If you have a suggestion I'd love to hear it! Maybe Google Forms would work as a free solution.

**Comment by SjorsWijsman** [comment]
Added the new Ashika Island map with the latest PR #25
